export const ALLERGIES = [
	"GLUTEN",
	"CRUSTACEANS",
	"EGGS",
	"FISH",
	"PEANUTS",
	"SOY",
	"DAIRY",
	"TREE_NUTS",
	"CELERY",
	"MUSTARD",
	"SESAME_SEEDS",
	"MOLLUSKS",
	"LUPINS",
	"LACTOSE",
	"COW_PROTEIN",
] as const;

export const ALLERGY_LABELS: Record<(typeof ALLERGIES)[number], string> = {
	GLUTEN: "Gluten",
	CRUSTACEANS: "Crustaceans",
	EGGS: "Eggs",
	FISH: "Fish",
	PEANUTS: "Peanuts",
	SOY: "Soy",
	DAIRY: "Dairy",
	TREE_NUTS: "Tree Nuts",
	CELERY: "Celery",
	MUSTARD: "Mustard",
	SESAME_SEEDS: "Sesame Seeds",
	MOLLUSKS: "Mollusks",
	LUPINS: "Lupins",
	LACTOSE: "Lactose",
	COW_PROTEIN: "Cow Protein",
};
